### PR TITLE
Update custom-console.md (How to use the unofficial custom console images)

### PR DESCRIPTION
**Pull request by benok**
Hi, I updated the doc about the custom consoles [as you suggests](https://github.com/burmilla/os/issues/126#issuecomment-1020798741).

English isn't my mother tongue. 
Please feel free to correct the expressions.

Thanks.

### CODE REVIEW

**Comment by benok** [comment]
Umm, I noticed the Fedora console can't be rebooted.

Please wait a moment to merge this. It's easy to stop supporting Fedora (as CentOS), but...

**Comment by benok** [comment]
> Umm, I noticed the Fedora console can't be rebooted.

I understand the problem.
If yum/dnf updates systemd, shutdown/reboot/halt symlink changes from ros to systemctl.
It's not a problem of the console image, but need some notes about this.

**Review by olljanat — APPROVED** [review]

**Comment by olljanat** [comment]
I think that this is fine. Can you open pull request against of https://github.com/burmilla/burmilla.github.io ?

**Comment by benok** [comment]
> I think that this is fine. Can you open pull request against of https://github.com/burmilla/burmilla.github.io ?

OMG, How fool I am!

**Pull request closed without merging**
